LBastidaCarga/Controllers/CargaController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace LBastidaCarga.Controllers
{
    public class CargaController : Controller
    {
        // GET: Carga
        public ActionResult Cargar()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Cargar(HttpPostedFileBase file)
        {
            file = Request.Files["CSV"];
            if (file != null && file.ContentLength > 0)
                try
                {

                    string extension = Path.GetExtension(file.FileName);
                    
                    string path = Path.Combine(Server.MapPath("~/"), Path.GetFileName(file.FileName));

                    BL.Producto.Carga(path);

                    
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return View();

           
        }


    }
}

LBastidaCarga/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LBastidaCarga.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LBastidaCarga/Views/Carga/Cargar.cshtml
@{
    ViewBag.Title = "Cargar";
}

<h2 class="text-center">Carga Masiva </h2>


<div class="row">
    <div class="col-md-6">
        <a><input type="submit" value="CSV" class="btn btn-success col-md-12" id="sel" /></a>
    </div>

</div>
@using (Html.BeginForm("Cargar", "Carga", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row g-3" id="fuImage" style="display:none;">
        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-file-earmark-text-fill" style="color: lightseagreen"></i></span>
                <input type='file' class="form-control" name="CSV" id="csv" />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">V</button>
}
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">

    $('#sel').click(function () {
        $('#fuImage').toggle('slow', function () {
        });
    });

    $(document).on('change', 'input[type=file]', function () {
        var filaName = this.files[0].name;
        var filaSize = this.files[0].size;

        var ext = filaName.split('.');
        ext = ext[ext.length - 1];

        switch (ext) {

            case 'csv':
                $('#tamanoArchivo').text(fileSize + " bytes " + ext);
                break;
            default:
                alert('El archivo no tiene la extensión adecuada(csv)');
                this.value = ''; // reset del valor
                this.files[0].name = '';
                break;
        }
    })



</script>

LBastidaCarga/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LBastidaCarga/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LBastidaCarga/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LBastidaCarga/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Cargar", "Cargar", "Carga")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>